version: "3"

services:
  install:
    image: node:boron
    container_name: slides-install
    command: npm install
    working_dir: /usr/src/app
    volumes:
      -  $PWD:/usr/src/app

  build-slides:
    image: node:boron
    container_name: slides-build
    command: npm run build
    working_dir: /usr/src/app
    volumes:
      -  $PWD:/usr/src/app

  server:
    image: node:boron
    container_name: slides-server
    command: npm start
    working_dir: /usr/src/app
    tty: true
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      -  $PWD:/usr/src/app
